### ISSUE TITLE
Debug information in executable

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#16]
Is it a good idea to contain the debug information in the executable?

Maybe better to split it into run-time related information (stored in the executable) and proper debug info (stored in the separate file as before)?

**Comment by bencz** [comment]
"Maybe better to split it into run-time related information (stored in the executable) and proper debug info (stored in the separate file as before)?"

It's the same of .net... :)
It is a good idea because the OS will have less information to load when you run, and debug information is only accessed by the IDE

**Comment by arakov** [comment]
Run-time type information should be relocated in this case

**Comment by arakov** [comment]
reopening

**Comment by arakov** [comment]
done
