### ISSUE TITLE
Compiler can't resolve full path of source to generate the object files

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#331]
There is a bug in compiler, if you try to build a project with the full path, the compiler duplicate the directory... for example:

E:\elena-project\src\main.l

when the compiler try to generate the object files, it's try to save in the directory:

E:\elena-project\src\E:\elena-project\src\main.nl

**Comment by bencz** [comment]
I have looked at this bug... But, I was thinking, if the system identifies creating an extension of a namespace by the directory, if we are using in the project the complete directory of source, it will create the following namespace:

Assuming that the namespace defined in the project is: project_test
source file: E:\elena-project\src\main.l
generated namespace: E'elena-project'src'project_test

**Comment by arakov** [comment]
That's why the path should be relative in the project :smile: 

We should start to build the module namespace starting from the project root path. If the file declared outside the project folder, the error should be raised.

The project root namespace should be the first. It is how the linker resolved the path to the class. If the namespace starts with the project one, it knows that it is a project module. If not, it will look into LIB31

**Comment by bencz** [comment]
So, will be better to force the IDE to always save the relative path

**Comment by arakov** [comment]
yes

**Comment by bencz** [comment]
Resolved int commit https://github.com/ELENA-LANG/elena-lang/commit/027790a8b04f73ee6a058f449b5229b7aedcae23
